/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thefinalproyect;

import java.io.File;

/**
 *
 * @author dam_9
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LArchivo = new javax.swing.JLabel();
        LCampos = new javax.swing.JLabel();
        LRegistros = new javax.swing.JLabel();
        LIndices = new javax.swing.JLabel();
        LEstandarizacion = new javax.swing.JLabel();
        LSalida = new javax.swing.JLabel();
        LSalida1 = new javax.swing.JLabel();
        PanelCambio = new javax.swing.JPanel();
        Archivo = new javax.swing.JPanel();
        bt_CrearArchivo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Campos = new javax.swing.JPanel();
        bt_CrearCampo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Registros = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Indices = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Estandar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ProyectoEDDII");
        setUndecorated(true);

        PanelPrincipal.setBackground(new java.awt.Color(0, 153, 153));
        PanelPrincipal.setForeground(new java.awt.Color(0, 153, 153));
        PanelPrincipal.setAutoscrolls(true);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        LArchivo.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        LArchivo.setForeground(new java.awt.Color(255, 255, 255));
        LArchivo.setText("\t\tArchivo");
        LArchivo.setToolTipText("");
        LArchivo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        LArchivo.setMaximumSize(new java.awt.Dimension(100, 100));
        LArchivo.setMinimumSize(new java.awt.Dimension(100, 100));
        LArchivo.setPreferredSize(new java.awt.Dimension(100, 100));
        LArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LArchivoMouseClicked(evt);
            }
        });

        LCampos.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        LCampos.setForeground(new java.awt.Color(255, 255, 255));
        LCampos.setText("Campos");
        LCampos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        LCampos.setMaximumSize(new java.awt.Dimension(100, 100));
        LCampos.setMinimumSize(new java.awt.Dimension(100, 100));
        LCampos.setPreferredSize(new java.awt.Dimension(100, 100));
        LCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LCamposMouseClicked(evt);
            }
        });

        LRegistros.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        LRegistros.setForeground(new java.awt.Color(255, 255, 255));
        LRegistros.setText("Registros");
        LRegistros.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        LRegistros.setMaximumSize(new java.awt.Dimension(100, 100));
        LRegistros.setMinimumSize(new java.awt.Dimension(100, 100));
        LRegistros.setPreferredSize(new java.awt.Dimension(100, 100));
        LRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LRegistrosMouseClicked(evt);
            }
        });

        LIndices.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        LIndices.setForeground(new java.awt.Color(255, 255, 255));
        LIndices.setText("Indices");
        LIndices.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        LIndices.setMaximumSize(new java.awt.Dimension(100, 100));
        LIndices.setMinimumSize(new java.awt.Dimension(100, 100));
        LIndices.setPreferredSize(new java.awt.Dimension(100, 100));
        LIndices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LIndicesMouseClicked(evt);
            }
        });

        LEstandarizacion.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        LEstandarizacion.setForeground(new java.awt.Color(255, 255, 255));
        LEstandarizacion.setText("Estandarizacion");
        LEstandarizacion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        LEstandarizacion.setMaximumSize(new java.awt.Dimension(100, 100));
        LEstandarizacion.setMinimumSize(new java.awt.Dimension(100, 100));
        LEstandarizacion.setPreferredSize(new java.awt.Dimension(100, 100));
        LEstandarizacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LEstandarizacionMouseClicked(evt);
            }
        });

        LSalida.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        LSalida.setForeground(new java.awt.Color(255, 255, 255));
        LSalida.setText("<html>DiegoMatamoros 11641131<br/>RicardoSanchez 11641051</html>");
        LSalida.setMaximumSize(new java.awt.Dimension(100, 100));
        LSalida.setMinimumSize(new java.awt.Dimension(100, 100));
        LSalida.setPreferredSize(new java.awt.Dimension(100, 100));
        LSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LSalidaMouseClicked(evt);
            }
        });

        LSalida1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LSalida1.setForeground(new java.awt.Color(255, 255, 255));
        LSalida1.setText("Salida");
        LSalida1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        LSalida1.setMaximumSize(new java.awt.Dimension(100, 100));
        LSalida1.setMinimumSize(new java.awt.Dimension(100, 100));
        LSalida1.setPreferredSize(new java.awt.Dimension(100, 100));
        LSalida1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LSalida1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LSalida1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LIndices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LSalida1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(LEstandarizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(LArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(LCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(LRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(LIndices, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(LEstandarizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LSalida1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelCambio.setBackground(new java.awt.Color(0, 153, 153));
        PanelCambio.setLayout(new java.awt.CardLayout());

        Archivo.setBackground(new java.awt.Color(0, 153, 204));
        Archivo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bt_CrearArchivo.setText("Crear Archivo");
        bt_CrearArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_CrearArchivoMouseClicked(evt);
            }
        });
        bt_CrearArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CrearArchivoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Archivo");

        javax.swing.GroupLayout ArchivoLayout = new javax.swing.GroupLayout(Archivo);
        Archivo.setLayout(ArchivoLayout);
        ArchivoLayout.setHorizontalGroup(
            ArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArchivoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(bt_CrearArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ArchivoLayout.createSequentialGroup()
                .addContainerGap(392, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(375, 375, 375))
        );
        ArchivoLayout.setVerticalGroup(
            ArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArchivoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(bt_CrearArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(602, Short.MAX_VALUE))
        );

        PanelCambio.add(Archivo, "card2");

        Campos.setBackground(new java.awt.Color(0, 153, 204));

        bt_CrearCampo.setText("CrearCampos");
        bt_CrearCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CrearCampoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setText("Campos");

        javax.swing.GroupLayout CamposLayout = new javax.swing.GroupLayout(Campos);
        Campos.setLayout(CamposLayout);
        CamposLayout.setHorizontalGroup(
            CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CamposLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(bt_CrearCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CamposLayout.createSequentialGroup()
                .addContainerGap(376, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(383, 383, 383))
        );
        CamposLayout.setVerticalGroup(
            CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CamposLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addComponent(bt_CrearCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(624, Short.MAX_VALUE))
        );

        PanelCambio.add(Campos, "card2");

        Registros.setBackground(new java.awt.Color(0, 153, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setText("Registros");

        javax.swing.GroupLayout RegistrosLayout = new javax.swing.GroupLayout(Registros);
        Registros.setLayout(RegistrosLayout);
        RegistrosLayout.setHorizontalGroup(
            RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrosLayout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(jLabel3)
                .addContainerGap(388, Short.MAX_VALUE))
        );
        RegistrosLayout.setVerticalGroup(
            RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrosLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addContainerGap(732, Short.MAX_VALUE))
        );

        PanelCambio.add(Registros, "card2");

        Indices.setBackground(new java.awt.Color(0, 153, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel4.setText("Indices");

        javax.swing.GroupLayout IndicesLayout = new javax.swing.GroupLayout(Indices);
        Indices.setLayout(IndicesLayout);
        IndicesLayout.setHorizontalGroup(
            IndicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IndicesLayout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(jLabel4)
                .addContainerGap(431, Short.MAX_VALUE))
        );
        IndicesLayout.setVerticalGroup(
            IndicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IndicesLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addContainerGap(732, Short.MAX_VALUE))
        );

        PanelCambio.add(Indices, "card2");

        Estandar.setBackground(new java.awt.Color(0, 153, 204));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel5.setText("Estandarizacion");

        javax.swing.GroupLayout EstandarLayout = new javax.swing.GroupLayout(Estandar);
        Estandar.setLayout(EstandarLayout);
        EstandarLayout.setHorizontalGroup(
            EstandarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstandarLayout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel5)
                .addContainerGap(318, Short.MAX_VALUE))
        );
        EstandarLayout.setVerticalGroup(
            EstandarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstandarLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel5)
                .addContainerGap(733, Short.MAX_VALUE))
        );

        PanelCambio.add(Estandar, "card2");

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 927, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LArchivoMouseClicked
        PanelCambio.removeAll();
        PanelCambio.repaint();
        PanelCambio.revalidate();

        PanelCambio.add(Archivo);
        PanelCambio.repaint();
        PanelCambio.revalidate();
    }//GEN-LAST:event_LArchivoMouseClicked

    private void bt_CrearCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CrearCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_CrearCampoActionPerformed

    private void LCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LCamposMouseClicked
        PanelCambio.removeAll();
        PanelCambio.repaint();
        PanelCambio.revalidate();

        PanelCambio.add(Campos);
        PanelCambio.repaint();
        PanelCambio.revalidate();
    }//GEN-LAST:event_LCamposMouseClicked

    private void LSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LSalidaMouseClicked
        System.exit(0);
    }//GEN-LAST:event_LSalidaMouseClicked

    private void LSalida1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LSalida1MouseClicked

    }//GEN-LAST:event_LSalida1MouseClicked

    private void LSalida1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LSalida1MousePressed
        System.exit(0);
    }//GEN-LAST:event_LSalida1MousePressed

    private void bt_CrearArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_CrearArchivoMouseClicked
        
    }//GEN-LAST:event_bt_CrearArchivoMouseClicked

    private void bt_CrearArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CrearArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_CrearArchivoActionPerformed

    private void LRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LRegistrosMouseClicked
       PanelCambio.removeAll();
        PanelCambio.repaint();
        PanelCambio.revalidate();

        PanelCambio.add(Registros);
        PanelCambio.repaint();
        PanelCambio.revalidate();
    }//GEN-LAST:event_LRegistrosMouseClicked

    private void LIndicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LIndicesMouseClicked
      PanelCambio.removeAll();
        PanelCambio.repaint();
        PanelCambio.revalidate();

        PanelCambio.add(Indices);
        PanelCambio.repaint();
        PanelCambio.revalidate();
    }//GEN-LAST:event_LIndicesMouseClicked

    private void LEstandarizacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LEstandarizacionMouseClicked
        PanelCambio.removeAll();
        PanelCambio.repaint();
        PanelCambio.revalidate();

        PanelCambio.add(Estandar);
        PanelCambio.repaint();
        PanelCambio.revalidate();
    }//GEN-LAST:event_LEstandarizacionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Archivo;
    private javax.swing.JPanel Campos;
    private javax.swing.JPanel Estandar;
    private javax.swing.JPanel Indices;
    private javax.swing.JLabel LArchivo;
    private javax.swing.JLabel LCampos;
    private javax.swing.JLabel LEstandarizacion;
    private javax.swing.JLabel LIndices;
    private javax.swing.JLabel LRegistros;
    private javax.swing.JLabel LSalida;
    private javax.swing.JLabel LSalida1;
    private javax.swing.JPanel PanelCambio;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel Registros;
    private javax.swing.JButton bt_CrearArchivo;
    private javax.swing.JButton bt_CrearCampo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    File ArchivoActual;
}
